version: '3.8'

services:
  # Local web server for tests
  web:
    image: nginx:alpine
    volumes:
      - .:/usr/share/nginx/html:ro
      - ./nginx.test.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "3000:80"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 5s
      timeout: 5s
      retries: 5

  # E2E test runner
  e2e-tests:
    build:
      context: .
      dockerfile: Dockerfile.e2e
    depends_on:
      web:
        condition: service_healthy
    environment:
      - BASE_URL=http://web
      - CI=true
    volumes:
      - ./playwright-report:/app/playwright-report
      - ./test-results:/app/test-results
    command: >
      sh -c "
        npm install &&
        npm install -D @playwright/test axe-playwright &&
        npx playwright install --with-deps &&
        npx playwright test --reporter=list,html
      "